Add nix support and updates for groundhog 0.10
The nix support has seen light testing with ghc 8.6.3.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -31,9 +31,12 @@ if [ -f $search ] ; then
     basedir=`pwd`/
 else if [ -f ../../../../../$search ] ; then
          basedir=../../../../../
-     else
-         echo "*** WARNING: $search not found";
-         exit 1;
+     else if [ -f ../../../../../../$search ] ; then
+	     basedir=../../../../../../
+         else
+             echo "*** WARNING: $search not found";
+             exit 1;
+          fi
      fi
 fi
 
